server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017
      database: xc_cms
  freemarker:
    cache: false #关闭模板缓存,方便测试
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 192.168.159.128
    username: leyou
    password: 123456
    virtual-host: /xuecheng
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
    publisher-confirms: true
eureka:
  client:
    register-with-eureka: true #服务注册，是否将自己注册到Eureka服务中
    fetch-registry: true #服务发现，是否从Eureka中获取注册信息
    service-url: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}