server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:123456@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 192.168.159.128
    username: leyou
    password: 123456
    virtual-host: /xuecheng
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: H:/xcEdu/video/
  ffmpeg-path: H:/xcEdu/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe